name: Maven Package Deploy

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Repository Checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          server-id: github
          cache: 'maven'

      - name: GitHub Packages Deploy
        run: mvn -B -DskipTests -Dpackage.version=${{ github.ref_name }} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
